trigger:
  batch: False
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - script: |
      call "%CONDA%\Scripts\activate" base
      echo "##vso[task.setvariable variable=PATH]%CONDA%\Scripts;%PATH%"
    displayName: Add conda to PATH and activate conda base
  - script: conda install -n base python=%PYTHON_VERSION% numpy
    displayName: Setup conda environment
  - bash: |
      python --version
      python setup.py install
    displayName: Install tdtpy
  - bash: |
      python -c "import tdt; print(tdt)"
    displayName: import tdt
