trigger:
  batch: False
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python311:
        python.version: '3.11'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      addToPath: true
    displayName: 'Get Python'
  - bash: |
      python --version
      python setup.py install
    displayName: Install tdtpy
  - bash: |
      python -c "import tdt; print(tdt)"
    displayName: import tdt
